

function getComputerChoice(){
    let randomInt=Math.floor(Math.random() * 3);
    let computerChoice;

    switch(randomInt){
        case 0:
            computerChoice="rock";
            break;
        case 1:
            computerChoice="paper";
            break;
        case 2:
            computerChoice="scissor";
            break;
        default:
            console.log("Invalid choice generated by the computer.");
    }
    console.log("Computer Choice: " +computerChoice);
    return computerChoice;
}

function getHumanChoice(){
    let humanInput = prompt("Enter your choice (Rock, Paper or Scissor)");
    let humanChoice = humanInput.toLowerCase();
    console.log("Your choice: " +humanChoice);
    return humanChoice;
}



function playGame(){
    let humanScore=0;
    let computerScore=0;
    
    function playRound(humanChoice, computerChoice){
        if(humanChoice===computerChoice){
            console.log("It's a draw!");
        }else if(humanChoice==="rock" && computerChoice==="paper"){
            console.log("You lose! Paper beats Rock.");
            computerScore += 1;
        }else if(humanChoice==="paper" && computerChoice==="scissor"){
            console.log("You lose! Scissor beats Paper.");
            computerScore += 1;
        }else if(humanChoice==="scissor" && computerChoice==="rock"){
            console.log("You lose! Rock beats Scissor.");
            computerScore += 1;
        }else if(humanChoice==="paper" && computerChoice==="rock"){
            console.log("You win! Paper beats Rock.");
            humanScore += 1;
        }else if(humanChoice==="scissor" && computerChoice==="paper"){
            console.log("You win! Scissor beats Paper.");
            humanScore += 1;
        }else if(humanChoice==="rock" && computerChoice==="scissor"){
            console.log("You win! Rock beats Scissor");
            humanScore += 1;
        }else{
            console.log("Unexpected error");
        }

        console.log("Your Score: " +humanScore);
        console.log("Computer Score: " +computerScore);
    }

    playRound(getHumanChoice(), getComputerChoice());
    playRound(getHumanChoice(), getComputerChoice());
    playRound(getHumanChoice(), getComputerChoice());
    playRound(getHumanChoice(), getComputerChoice());
    playRound(getHumanChoice(), getComputerChoice());
}

playGame();