

function getComputerChoice(){
    let randomInt=Math.floor(Math.random() * 3);
    let computerChoice;

    switch(randomInt){
        case 0:
            computerChoice="rock";
            break;
        case 1:
            computerChoice="paper";
            break;
        case 2:
            computerChoice="scissor";
            break;
        default:
            console.log("Invalid choice generated by the computer.");
    }
    
    return computerChoice;
    
}

let humanScore = 0;
let computerScore = 0;
let roundCount = 0;

const rockbtn = document.getElementById("rock");
const paperbtn = document.getElementById("paper");
const scissorbtn = document.getElementById("scissor");

rockbtn.addEventListener("click", function(){
    playRound(rockbtn.id);
});

paperbtn.addEventListener("click", function (){
    playRound(paperbtn.id);
});

scissorbtn.addEventListener("click", function(){
    playRound(scissorbtn.id);
});

function playRound(humanChoice){

    if(roundCount >=5) return;

    roundCount++;
    
    let computerChoice = getComputerChoice();
    
    document.getElementById("round-no").textContent = roundCount;
    document.getElementById("human-choice").textContent = humanChoice;
    document.getElementById("computer-choice").textContent = computerChoice;

    if(humanChoice===computerChoice){
        document.getElementById("round-message").textContent = "It's a draw!";
        
    }else if(humanChoice==="rock" && computerChoice==="paper"){
        document.getElementById("round-message").textContent ="You lose! Paper beats Rock.";
        computerScore += 1;

    }else if(humanChoice==="paper" && computerChoice==="scissor"){
        document.getElementById("round-message").textContent = "You lose! Scissor beats Paper.";
        computerScore += 1;

    }else if(humanChoice==="scissor" && computerChoice==="rock"){
        document.getElementById("round-message").textContent = "You lose! Rock beats Scissor.";
        computerScore += 1;

    }else if(humanChoice==="paper" && computerChoice==="rock"){
        document.getElementById("round-message").textContent = "You win! Paper beats Rock.";
        humanScore += 1;

    }else if(humanChoice==="scissor" && computerChoice==="paper"){
        document.getElementById("round-message").textContent = "You win! Scissor beats Paper.";
        humanScore += 1;

    }else if(humanChoice==="rock" && computerChoice==="scissor"){
        document.getElementById("round-message").textContent = "You win! Rock beats Scissor";
        humanScore += 1;

    }else{
        console.log("Unexpected error");
    }

    document.getElementById("human-score").textContent = humanScore;
    document.getElementById("computer-score").textContent = computerScore;

    if(roundCount === 5){
        endGame();
    }
}

function endGame(){
    if (humanScore > computerScore){
        document.getElementById("final-message").textContent = "You Win!";
    }else if(computerScore > humanScore){
        document.getElementById("final-message").textContent = "You lose!";
    }else{
        document.getElementById("final-message").textContent = "It's a Tie";
    }
}