

// function getComputerChoice(){
//     let randomInt=Math.floor(Math.random() * 3);
//     let computerChoice;

//     switch(randomInt){
//         case 0:
//             computerChoice="rock";
//             break;
//         case 1:
//             computerChoice="paper";
//             break;
//         case 2:
//             computerChoice="scissor";
//             break;
//         default:
//             console.log("Invalid choice generated by the computer.");
//     }
    
//     return computerChoice;
    
// }

// let humanScore = 0;
// let computerScore = 0;
// let roundCount = 0;

// const rockbtn = document.getElementById("rock");
// const paperbtn = document.getElementById("paper");
// const scissorbtn = document.getElementById("scissor");

// rockbtn.addEventListener("click", function(){
//     playRound(rockbtn.id);
// });

// paperbtn.addEventListener("click", function (){
//     playRound(paperbtn.id);
// });

// scissorbtn.addEventListener("click", function(){
//     playRound(scissorbtn.id);
// });

// function playRound(humanChoice){

//     if(roundCount >=5) return;

//     roundCount++;
    
//     let computerChoice = getComputerChoice();
    
//     document.getElementById("round-no").textContent = roundCount;
//     document.getElementById("human-choice").textContent = humanChoice;
//     document.getElementById("computer-choice").textContent = computerChoice;

//     if(humanChoice===computerChoice){
//         document.getElementById("round-message").textContent = "It's a draw!";
        
//     }else if(humanChoice==="rock" && computerChoice==="paper"){
//         document.getElementById("round-message").textContent ="You lose! Paper beats Rock.";
//         computerScore += 1;

//     }else if(humanChoice==="paper" && computerChoice==="scissor"){
//         document.getElementById("round-message").textContent = "You lose! Scissor beats Paper.";
//         computerScore += 1;

//     }else if(humanChoice==="scissor" && computerChoice==="rock"){
//         document.getElementById("round-message").textContent = "You lose! Rock beats Scissor.";
//         computerScore += 1;

//     }else if(humanChoice==="paper" && computerChoice==="rock"){
//         document.getElementById("round-message").textContent = "You win! Paper beats Rock.";
//         humanScore += 1;

//     }else if(humanChoice==="scissor" && computerChoice==="paper"){
//         document.getElementById("round-message").textContent = "You win! Scissor beats Paper.";
//         humanScore += 1;

//     }else if(humanChoice==="rock" && computerChoice==="scissor"){
//         document.getElementById("round-message").textContent = "You win! Rock beats Scissor";
//         humanScore += 1;

//     }else{
//         console.log("Unexpected error");
//     }

//     document.getElementById("human-score").textContent = humanScore;
//     document.getElementById("computer-score").textContent = computerScore;

//     if(roundCount === 5){
//         endGame();
//     }
// }

// function endGame(){
//     if (humanScore > computerScore){
//         document.getElementById("final-message").textContent = "You Win!";
//     }else if(computerScore > humanScore){
//         document.getElementById("final-message").textContent = "You lose!";
//     }else{
//         document.getElementById("final-message").textContent = "It's a Tie";
//     }
// }

let botScore = 0;
let playerScore = 0;

getPlayerChoice()

function generateBotChoice(){
    let randomInt = Math.floor(Math.random() * 3);
    let botChoice;

    switch(randomInt){
        case 0:
            botChoice = "rock";
            break;
        case 1:
            botChoice = "paper";
            break;
        case 2:
            botChoice = "scissor";
            break;
        default:
            console.log("Bot choice generated incorrectly");
    }

    return botChoice;
}

function displayBotChoice(botChoice){
    const botChoiceImage = document.querySelector(".bot_choice");   
    

    if(botChoice === "rock"){
        botChoiceImage.src = "../images/rock.svg";
        botChoiceImage.style.height = "20px";
    }else if(botChoice === "paper"){
        botChoiceImage.src = "../images/paper.svg";
        botChoiceImage.style.height = "20px";
    }else{
        botChoiceImage.src = "../images/scissor.svg";
        botChoiceImage.style.height = "20px";
    }    
}

function getPlayerChoice(){
    const inputButtons = document.querySelectorAll(".player_input_button");
    inputButtons.forEach((inputButton) => {
        inputButton.addEventListener("click", () => {

            const playerChoice = inputButton.firstElementChild.classList[0];
            console.log(`playerChoice ${playerChoice}`);
            displayPlayerChoice(playerChoice);

            playGame(playerChoice);
        });
    });       
}

function displayPlayerChoice(playerChoice){
    const playerChoiceImage = document.querySelector(".player_choice");   
    

    if(playerChoice === "rock"){
        playerChoiceImage.src = "../images/rock.svg";
        playerChoiceImage.style.height = "20px";
    }else if(playerChoice === "paper"){
        playerChoiceImage.src = "../images/paper.svg";
        playerChoiceImage.style.height = "20px";
    }else{
        playerChoiceImage.src = "../images/scissor.svg";
        playerChoiceImage.style.height = "20px";
    }    
}

function playGame(playerChoice){
    
    let botChoice = generateBotChoice();
    console.log(`botChoice ${botChoice}`);
    displayBotChoice(botChoice);
    

    if(playerChoice === botChoice){
        console.log("Its a tie");
    }

    if((playerChoice === "rock" && botChoice === "paper") ||
       (playerChoice === "paper" && botChoice === "scissor") ||
       (playerChoice === "scissor" && botChoice === "rock")){
        console.log("This rounds winner is the bot");
        botScore++;
    }
    
    if((botChoice === "rock" && playerChoice === "paper") ||
       (botChoice === "paper" && playerChoice === "scissor") ||
       (botChoice === "scissor" && playerChoice === "rock")){
        console.log("This rounds winner is you");
        playerScore++;
    }

    console.log(`botScore: ${botScore}`);
    console.log(`playerScore: ${playerScore}`);

    if(botScore === 5 || playerScore === 5){
        if(botScore === 5){
            console.log("Bot wins the entire game");
        }else{
            console.log("Yoy win the entire game");
        }

        
    }
}



